{% set name = "spyder-notebook" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 01c018a63576d0c255eea3b927e1bfa7cbf017a7d6e585957ac4794bcc3c0e6c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - spyder >=6,<7
    - jupyter_core
    - jupyter_server
    - nbformat
    - notebook >=7.3.3,<7.4
    - psutil
    - qdarkstyle
    - qtpy
    - requests
    - tornado
    - traitlets

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - python -m pip check  # [linux or win]
  imports:
    # Linux is giving a segfault probably due to the lack of an X server
    # OS X fails to due some issue with Qt unrelated to this recipe
    - spyder_notebook  # [win]

about:
  home: https://github.com/spyder-ide/spyder-notebook
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter notebook integration with Spyder
  description: |
    Currently it supports basic functionality such as creating new notebooks, 
    opening any notebook in your filesystem and saving notebooks at any location.
  dev_url: https://github.com/spyder-ide/spyder-notebook

extra:
  recipe-maintainers:
    - dalthviz
    - ccordoba12
    - jitseniesen
