{% set name = "spyder-notebook" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 770022db877709eeed7a9e544fe86bf47f528ade7eb80ba22ea5b4beb087f469

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    - spyder >=4,<5
    - notebook >=4.3
    - qtpy
    - requests
    - psutil
    - nbformat

test:
  imports:
    # Linux is giving a segfault probably due to the lack of an X server
    # OS X fails to due some issue with Qt unrelated to this recipe
    - spyder_notebook  # [win]

about:
  home: https://github.com/spyder-ide/spyder-notebook
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter notebook integration with Spyder
  description: |
    Currently it supports basic functionality such as creating new notebooks, 
    opening any notebook in your filesystem and saving notebooks at any location.
  dev_url: https://github.com/spyder-ide/spyder-notebook

extra:
  recipe-maintainers:
    - dalthviz
    - ccordoba12
    - jitseniesen
