{% set name = "spyder-notebook" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e8e778a85068dc0f40bddff569ab8447db16f318c9f41ae9d1138f1d95c0859

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python >=3.7
    - spyder >=5.4.3,<6
    - jupyter_core
    - jupyter_server
    - nbformat
    - notebook >=7,<8
    - qdarkstyle
    - qtpy
    - requests
    - tornado
    - traitlets

test:
  requires:
    - pip
  commands:
    - python -m pip check  # [linux or win]
  imports:
    # Linux is giving a segfault probably due to the lack of an X server
    # OS X fails to due some issue with Qt unrelated to this recipe
    - spyder_notebook  # [win]

about:
  home: https://github.com/spyder-ide/spyder-notebook
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter notebook integration with Spyder
  description: |
    Currently it supports basic functionality such as creating new notebooks, 
    opening any notebook in your filesystem and saving notebooks at any location.
  dev_url: https://github.com/spyder-ide/spyder-notebook

extra:
  recipe-maintainers:
    - dalthviz
    - ccordoba12
    - jitseniesen
