{% set name = "spyder-notebook" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 444c269b89077f625b311e220e86fd77675e147c2943f45a1f5769a6d5fc65a0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python >=3.5
    - spyder >=4.1,<5
    - jinja2
    - jupyter_core
    - nbformat
    - notebook >=4.3
    - qdarkstyle
    - qtpy
    - requests
    - traitlets

test:
  imports:
    # Linux is giving a segfault probably due to the lack of an X server
    # OS X fails to due some issue with Qt unrelated to this recipe
    - spyder_notebook  # [win]

about:
  home: https://github.com/spyder-ide/spyder-notebook
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter notebook integration with Spyder
  description: |
    Currently it supports basic functionality such as creating new notebooks, 
    opening any notebook in your filesystem and saving notebooks at any location.
  dev_url: https://github.com/spyder-ide/spyder-notebook

extra:
  recipe-maintainers:
    - dalthviz
    - ccordoba12
    - jitseniesen
