{% set name = "spyder-notebook" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 18f329f2fbd29c680b8a885397ffaf160e9b5dd1ff8cf4c40313d3ef56319952

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python >=3.8
    - spyder >=6,<7
    - jupyter_core
    - jupyter_server
    - nbformat
    - notebook >=7.2,<8
    - qdarkstyle
    - qtpy
    - requests
    - tornado
    - traitlets

test:
  requires:
    - pip
  commands:
    - python -m pip check  # [linux or win]
  imports:
    # Linux is giving a segfault probably due to the lack of an X server
    # OS X fails to due some issue with Qt unrelated to this recipe
    - spyder_notebook  # [win]

about:
  home: https://github.com/spyder-ide/spyder-notebook
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter notebook integration with Spyder
  description: |
    Currently it supports basic functionality such as creating new notebooks, 
    opening any notebook in your filesystem and saving notebooks at any location.
  dev_url: https://github.com/spyder-ide/spyder-notebook

extra:
  recipe-maintainers:
    - dalthviz
    - ccordoba12
    - jitseniesen
