travis:
  secure:
    BINSTAR_TOKEN: mosMQnTU+x4Md8Lbg4Oy5JT02WpYOCQZzhw86nIZrtGqbEwD+U1s8YoZJ0OOwuMQSMsDreJS4RBevb5GyvDNX9GHH6M6peuZIOCN8ygQb/Wydh4QE79FJXnmDCqMBtiXP1XDas9x+ZK+wpNzzRljlbAnaKtJHFCSI8LDoZjmQ/Ez6vITFNDDHPSrK9kFftqde2f2rkZu2jVNt/tsb09QO9r8AikIm1J7kO5A4BudW79VtnaIqs3YZY5RUe0jiDM6qaE4uNWm4IP7zIxnpJpPs+ycZmF0Yr6KJd/rmvg4Pd9yuviGfSTz+2j6rVUb9TJOw1AAhZ9Em68TeB1kA/PPZFC+owV93Dmv4q5RmRRy+b/xVUU6ehpmYbe2wD6JLB13ldUbHG8Ky9vUVJmV06DML/YbnhqTZsq+YSQLLVjEK2xlZbOsSdRvGUKr8OiWPZFFpIxNLqQshYl078jrdXVV+QEpt/DUryGMIxbFcnxVzdPMsHJt5ZD8l6bFjUtejHvtgtCEFddGQ1bywFQpccILVgR8n7KAJBitwNe4HjOzOaYHdvqhQ196LkUui3j7sRz5oG5J5M+/hqIFM+OyVFH+5xEcxxraD30oL7q3VI28wtHbfMKQRXNSfSuxYZ4s6XvyvpeYgBMro05G+ZWT+NV+6BruhiNSBzrK2fXhzqr4wLQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
